name: Auto Comment

on:
  issues:
    types: [opened]
jobs:
  auto-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install wow-actions/auto-comment
        uses: wow-actions/auto-comment@v1

      - name: Run auto-comment
        uses: wow-actions/auto-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            Hello @{​​​​​​​​{​​​​​​​​github.event.issue.user.login}​​​​​​​​}​​​​​​​​!
            Thank you for opening this issue. Could you please provide more context or steps to reproduce the problem? We'll be happy to assist you further.
